# generated by gen_led_data.py (do not edit); proofs run at generation time
    .data
# palette: colour index -> 0x00RRGGBB, order W Y G B O R
PALETTE:
    .word 0xFFFFFF,0xFFFF00,0x00C800,0x0000FF,0xFF8000,0xFF0000
# COLOR[(cubie*3 + twist)*3 + slot]: colour index of the sticker in `slot` of a position
COLOR:
    .byte 0,5,2,5,2,0,2,0,5,1,2,5
    .byte 2,5,1,5,1,2,1,4,2,4,2,1
    .byte 2,1,4,0,3,5,3,5,0,5,0,3
    .byte 1,5,3,5,3,1,3,1,5,1,3,4
    .byte 3,4,1,4,1,3,0,4,3,4,3,0
    .byte 3,0,4
# PIX[idx*3 + slot]: byte offset ((y*35 + x)*4) of the top-left pixel of the 4x3 facelet cell, idx = position - 1
    .align 1
PIX:
    .half 472,1052,1032,2012,1452,1472,1996,1416,1436
    .half 52,1088,1068,2432,1488,1508,2416,1524,1400
    .half 36,980,1104
# FIXED: the fixed corner (offset .half, colour .half) x 3, drawn once
    .align 1
FIXED:
    .half 456,0,1016,2,996,4
# move tables of solver.c: SRC[face*7 + i], TW[face*7 + i]; move m = face*3 + turns - 1
SRC:
    .byte 1,4,2,0,3,5,6,0,1,2,4,5
    .byte 6,3,0,2,5,3,1,4,6
TW:
    .byte 1,2,0,2,1,0,0,0,0,0,1,2
    .byte 1,2,0,0,0,0,0,0,0
MOVEF:
    .byte 0,0,0,1,1,1,2,2,2
MOVET:
    .byte 1,2,3,1,2,3,1,2,3
# test case: the state string (override with make STATE=...) and the dummy solver answer
#ifdef TEST_STATE
STATE:
    .asciz TEST_STATE
#else
STATE:
    .asciz "41625372313211"
#endif
DUMMYPATH:
    .byte 2,6,2,3,6,4,2,6,3,7,5
    .align 2
EXPECT_SUMS:
    .word 0xBC6E7070,0x1186E990,0xC7D1CDB2,0xC533303C,0x174593DA,0x16CD74E1,0xFB9B2C91,0x51ED94FA,0x4D45B480,0x120B25C9,0xCA3F4D24,0x3413F6D1
