# generated by gen_led_data.py (do not edit); proofs run at generation time
    .data
# palette: colour index -> 0x00RRGGBB, order W Y G B O R
PALETTE:
    .word 0xFFFFFF,0xFFFF00,0x00C800,0x0000FF,0xFF8000,0xFF0000
# COLOR[(cubie*3 + twist)*3 + slot]: colour index of the sticker in `slot` of a position
COLOR:
    .byte 0,5,2,5,2,0,2,0,5,1,2,5
    .byte 2,5,1,5,1,2,1,4,2,4,2,1
    .byte 2,1,4,0,3,5,3,5,0,5,0,3
    .byte 1,5,3,5,3,1,3,1,5,1,3,4
    .byte 3,4,1,4,1,3,0,4,3,4,3,0
    .byte 3,0,4
# PIX[idx*3 + slot]: byte offset ((y*35 + x)*4) of the 4x3 facelet block, idx = position - 1
PIX:
    .half 472,1052,1032,2012,1452,1472,1996,1416,1436
    .half 52,1088,1068,2432,1488,1508,2416,1524,1400
    .half 36,980,1104
# FIXED: the fixed corner (offset .half, colour .half) x 3, drawn once
FIXED:
    .half 456,0,1016,2,996,4
# move tables of solver.c: SRC[face*7 + i], TW[face*7 + i]; move m = face*3 + turns - 1
SRC:
    .byte 1,4,2,0,3,5,6,0,1,2,4,5
    .byte 6,3,0,2,5,3,1,4,6
TW:
    .byte 1,2,0,2,1,0,0,0,0,0,1,2
    .byte 1,2,0,0,0,0,0,0,0
MOVEF:
    .byte 0,0,0,1,1,1,2,2,2
MOVET:
    .byte 1,2,3,1,2,3,1,2,3
# dummy test case
STATE:
    .asciz "21345671111111"
DUMMYPATH:
    .byte 0,5,7,2,3,2,5,0,7,0,3
    .align 2
EXPECT_SUMS:
    .word 0x4EB44E87,0xD7E2D4C3,0x0EECF9A0,0xB0E0A2A7,0x470EA9F1,0x398836D2,0x5A8A89B7,0xDE1B5738,0x9BB1FC1A,0x4B7D191C,0xD7AE2ADB,0x03297E54
